### ISSUE TITLE
The category page doesn't work on the template

### ISSUE THREAD

**Issue by gregatgoogle** [unitedforukraine/signpost-template#52]
## Reproduction

1. `yarn dev`
2. Visit a category page, http://localhost:3000/en-us/categories/123.

You'll see

```
error - TypeError: Cannot read properties of undefined (reading 'appId')
    at SearchBar (webpack-internal:///./node_modules/@ircsignpost/signpost-base/dist/src/search-bar.js:48:86)
    at renderWithHooks (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/grzegorzmilka/u4u/signpost-template/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14) {
  page: '/categories/[category]'
```

**Comment by EOkoyomon** [comment]
Following the repro steps, I dont get the same issue.. Did you run yarn install?
